//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuestInformation()
        {
            this.PaymentInfo = new HashSet<PaymentInfo>();
            this.ReservationInfo = new HashSet<ReservationInfo>();
        }
    
        public int guestID { get; set; }
        public string guestFirstName { get; set; }
        public string guestLastName { get; set; }
        public Nullable<System.DateTime> guestBirthDate { get; set; }
        public string guestGender { get; set; }
        public string guestContactNo { get; set; }
        public string guestAddress { get; set; }
        public string guestEmailAddress { get; set; }
        public System.DateTime guestLastCheckInDate { get; set; }
        public System.DateTime guestLastCheckOutDate { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> roomID { get; set; }
    
        public virtual RoomInformation RoomInformation { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentInfo> PaymentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationInfo> ReservationInfo { get; set; }
    }
}
